-- Initial seed only. Safe to rerun: never resets player progress or edited settings.
DO $seed$ BEGIN
IF EXISTS (SELECT 1 FROM spunk.settings WHERE id=1) THEN RETURN; END IF;
INSERT INTO spunk.items VALUES ('angry-ash','Angry Ash','LEGENDARY','/assets/items/angry-ash.webp');
INSERT INTO spunk.items VALUES ('drag-ttg','Drag TTG','LEGENDARY','/assets/items/drag-ttg.webp');
INSERT INTO spunk.items VALUES ('mike-andy-and-shuan','mike andy and shuan','LEGENDARY','/assets/items/mike-andy-and-shuan.webp');
INSERT INTO spunk.items VALUES ('mini-men','mini men','MYTHIC','/assets/items/mini-men.webp');
INSERT INTO spunk.items VALUES ('ttg-nip-slip','TTG NIP SLIP','MYTHIC','/assets/items/ttg-nip-slip.webp');
INSERT INTO spunk.items VALUES ('chicken-troopers','chicken troopers','EPIC','/assets/items/chicken-troopers.webp');
INSERT INTO spunk.items VALUES ('jamie-g','Jamie G','EPIC','/assets/items/jamie-g.webp');
INSERT INTO spunk.items VALUES ('johnpork','johnpork','EPIC','/assets/items/johnpork.webp');
INSERT INTO spunk.items VALUES ('wonkey-ash','wonkey ash','EPIC','/assets/items/wonkey-ash.webp');
INSERT INTO spunk.items VALUES ('leonardo','leonardo','RARE','/assets/items/leonardo.webp');
INSERT INTO spunk.items VALUES ('mike','mike','RARE','/assets/items/mike.webp');
INSERT INTO spunk.items VALUES ('pencil-arms-ash','pencil arms ash','RARE','/assets/items/pencil-arms-ash.webp');
INSERT INTO spunk.items VALUES ('surfing-haz','surfing haz','RARE','/assets/items/surfing-haz.webp');
INSERT INTO spunk.items VALUES ('ttgdressup','TTGDRESSup','RARE','/assets/items/ttgdressup.webp');
INSERT INTO spunk.items VALUES ('chud-zac','Chud Zac','UNCOMMON','/assets/items/chud-zac.webp');
INSERT INTO spunk.items VALUES ('dodgyhaz','dodgyHaz','UNCOMMON','/assets/items/dodgyhaz.webp');
INSERT INTO spunk.items VALUES ('hardhat-zac','HardHat Zac','UNCOMMON','/assets/items/hardhat-zac.webp');
INSERT INTO spunk.items VALUES ('shuan','Shuan','UNCOMMON','/assets/items/shuan.webp');
INSERT INTO spunk.items VALUES ('cashire-ttg','Cashire TTG','COMMON','/assets/items/cashire-ttg.webp');
INSERT INTO spunk.items VALUES ('forkbev','ForkBev','COMMON','/assets/items/forkbev.webp');
INSERT INTO spunk.items VALUES ('tony','Tony','COMMON','/assets/items/tony.webp');
INSERT INTO spunk.items VALUES ('ttg','TTG','COMMON','/assets/items/ttg.webp');
INSERT INTO spunk.items VALUES ('ash-ash-paffet','ash paffet','UNCOMMON','/assets/items/ash-ash-paffet.webp');
INSERT INTO spunk.items VALUES ('ash-aura-farm-ash','Aura Farm ash','MYTHIC','/assets/items/ash-aura-farm-ash.webp');
INSERT INTO spunk.items VALUES ('ash-bald-ash','Bald ash','RARE','/assets/items/ash-bald-ash.webp');
INSERT INTO spunk.items VALUES ('ash-bannana-ash','Bannana Ash','COMMON','/assets/items/ash-bannana-ash.webp');
INSERT INTO spunk.items VALUES ('ash-blue-bag-ash','blue bag ash','COMMON','/assets/items/ash-blue-bag-ash.webp');
INSERT INTO spunk.items VALUES ('ash-caveman-ash','caveman ash','UNCOMMON','/assets/items/ash-caveman-ash.webp');
INSERT INTO spunk.items VALUES ('ash-cheeky-ash','Cheeky ash','UNCOMMON','/assets/items/ash-cheeky-ash.webp');
INSERT INTO spunk.items VALUES ('ash-chocolate-milk-ash','Chocolate milk ash','RARE','/assets/items/ash-chocolate-milk-ash.webp');
INSERT INTO spunk.items VALUES ('ash-clipper-ash','Clipper Ash','EPIC','/assets/items/ash-clipper-ash.webp');
INSERT INTO spunk.items VALUES ('ash-egg-ash','Egg Ash','LEGENDARY','/assets/items/ash-egg-ash.webp');
INSERT INTO spunk.items VALUES ('ash-football-ash','Football ash','LEGENDARY','/assets/items/ash-football-ash.webp');
INSERT INTO spunk.items VALUES ('ash-frustrated-ash','Frustrated Ash','EPIC','/assets/items/ash-frustrated-ash.webp');
INSERT INTO spunk.items VALUES ('ash-gate-ash','Gate Ash','COMMON','/assets/items/ash-gate-ash.webp');
INSERT INTO spunk.items VALUES ('ash-goalkeeper-ash','Goalkeeper ash','EPIC','/assets/items/ash-goalkeeper-ash.webp');
INSERT INTO spunk.items VALUES ('ash-horny-ash','Horny ash','MYTHIC','/assets/items/ash-horny-ash.webp');
INSERT INTO spunk.items VALUES ('ash-hotdog-ash','Hotdog ash','EPIC','/assets/items/ash-hotdog-ash.webp');
INSERT INTO spunk.items VALUES ('ash-mars-bar-ash','Mars Bar Ash','RARE','/assets/items/ash-mars-bar-ash.webp');
INSERT INTO spunk.items VALUES ('ash-obese-ash','obese ash','LEGENDARY','/assets/items/ash-obese-ash.webp');
INSERT INTO spunk.items VALUES ('ash-posture-ash','posture ash','LEGENDARY','/assets/items/ash-posture-ash.webp');
INSERT INTO spunk.items VALUES ('ash-rude-ash','Rude Ash','EPIC','/assets/items/ash-rude-ash.webp');
INSERT INTO spunk.items VALUES ('ash-sleepy-ash','Sleepy Ash','RARE','/assets/items/ash-sleepy-ash.webp');
INSERT INTO spunk.items VALUES ('ash-seductive-ash','Seductive Ash','UNCOMMON','/assets/items/ash-seductive-ash.webp');
INSERT INTO spunk.items VALUES ('ash-supercool-young-ash','Supercool Young Ash','EPIC','/assets/items/ash-supercool-young-ash.webp');
INSERT INTO spunk.items VALUES ('ash-taking-it-ash','Taking it ash','MYTHIC','/assets/items/ash-taking-it-ash.webp');
INSERT INTO spunk.items VALUES ('ash-the-gang-ash','The Gang ash','LEGENDARY','/assets/items/ash-the-gang-ash.webp');
INSERT INTO spunk.items VALUES ('ash-thumbs-up-ash','Thumbs up ash','EPIC','/assets/items/ash-thumbs-up-ash.webp');
INSERT INTO spunk.items VALUES ('ash-ttt-ash','TTT ash','RARE','/assets/items/ash-ttt-ash.webp');
INSERT INTO spunk.items VALUES ('ash-workout-ash','Workout ash','RARE','/assets/items/ash-workout-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-a-h','A&H','RARE','/assets/items/satchel-a-h.webp');
INSERT INTO spunk.items VALUES ('satchel-ash-kyle-show','Ash kyle show','EPIC','/assets/items/satchel-ash-kyle-show.webp');
INSERT INTO spunk.items VALUES ('satchel-bathtub-boys','Bathtub boys','EPIC','/assets/items/satchel-bathtub-boys.webp');
INSERT INTO spunk.items VALUES ('satchel-bev-and-the-bean-stalk','Bev and the Bean Stalk','LEGENDARY','/assets/items/satchel-bev-and-the-bean-stalk.webp');
INSERT INTO spunk.items VALUES ('satchel-biker-bev','Biker bev','RARE','/assets/items/satchel-biker-bev.webp');
INSERT INTO spunk.items VALUES ('satchel-boys-4-life','Boys 4 Life','LEGENDARY','/assets/items/satchel-boys-4-life.webp');
INSERT INTO spunk.items VALUES ('satchel-bright-future','Bright Future','EPIC','/assets/items/satchel-bright-future.webp');
INSERT INTO spunk.items VALUES ('satchel-dodgy-elevator-ride','Dodgy Elevator ride','RARE','/assets/items/satchel-dodgy-elevator-ride.webp');
INSERT INTO spunk.items VALUES ('satchel-erm-idk','Erm IDK','RARE','/assets/items/satchel-erm-idk.webp');
INSERT INTO spunk.items VALUES ('satchel-game-time','Game Time','EPIC','/assets/items/satchel-game-time.webp');
INSERT INTO spunk.items VALUES ('satchel-happy-zac','Happy Zac','RARE','/assets/items/satchel-happy-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-ima-celeb-ttg','Ima Celeb TTG','EPIC','/assets/items/satchel-ima-celeb-ttg.webp');
INSERT INTO spunk.items VALUES ('satchel-mafia','Mafia','LEGENDARY','/assets/items/satchel-mafia.webp');
INSERT INTO spunk.items VALUES ('satchel-nerf-gun-ttg','Nerf Gun TTG','RARE','/assets/items/satchel-nerf-gun-ttg.webp');
INSERT INTO spunk.items VALUES ('satchel-packet-man','Packet man','UNCOMMON','/assets/items/satchel-packet-man.webp');
INSERT INTO spunk.items VALUES ('satchel-postman-jay','Postman Jay','UNCOMMON','/assets/items/satchel-postman-jay.webp');
INSERT INTO spunk.items VALUES ('satchel-shocked-ttg','Shocked TTG','COMMON','/assets/items/satchel-shocked-ttg.webp');
INSERT INTO spunk.items VALUES ('satchel-ttg-funeral','TTG FUNERAL','LEGENDARY','/assets/items/satchel-ttg-funeral.webp');
INSERT INTO spunk.items VALUES ('satchel-ttg-files','TTG Files','MYTHIC','/assets/items/satchel-ttg-files.webp');
INSERT INTO spunk.items VALUES ('satchel-ttg-s-football-club','TTG''s Football club','LEGENDARY','/assets/items/satchel-ttg-s-football-club.webp');
INSERT INTO spunk.items VALUES ('satchel-thumbs-up-ash','Thumbs up ash','COMMON','/assets/items/satchel-thumbs-up-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-tiktok-live-ttg','TikTok Live TTG','EPIC','/assets/items/satchel-tiktok-live-ttg.webp');
INSERT INTO spunk.items VALUES ('satchel-w-rizz','W RIZZ','LEGENDARY','/assets/items/satchel-w-rizz.webp');
INSERT INTO spunk.items VALUES ('satchel-wise-ttg-words','Wise TTg words','RARE','/assets/items/satchel-wise-ttg-words.webp');
INSERT INTO spunk.items VALUES ('satchel-alien-abduction-zac','alien abduction zac','MYTHIC','/assets/items/satchel-alien-abduction-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-bird-zac','bird zac','RARE','/assets/items/satchel-bird-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-cheeky-ash','cheeky ash','UNCOMMON','/assets/items/satchel-cheeky-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-chicken-bomber','chicken Bomber','EPIC','/assets/items/satchel-chicken-bomber.webp');
INSERT INTO spunk.items VALUES ('satchel-corona-ash','corona ash','UNCOMMON','/assets/items/satchel-corona-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-dodgy-zac','dodgy zac','COMMON','/assets/items/satchel-dodgy-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-dont-get-cuaght','dont get cuaght','COMMON','/assets/items/satchel-dont-get-cuaght.webp');
INSERT INTO spunk.items VALUES ('satchel-double-thumbs-up-ash','double thumbs up ash','UNCOMMON','/assets/items/satchel-double-thumbs-up-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-drunk-haz','drunk haz','UNCOMMON','/assets/items/satchel-drunk-haz.webp');
INSERT INTO spunk.items VALUES ('satchel-dumptruck-zac','dumptruck zac','RARE','/assets/items/satchel-dumptruck-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-fat-slob','fat slob','COMMON','/assets/items/satchel-fat-slob.webp');
INSERT INTO spunk.items VALUES ('satchel-harry-myatt','harry myatt','UNCOMMON','/assets/items/satchel-harry-myatt.webp');
INSERT INTO spunk.items VALUES ('satchel-headset-liam','headset liam','COMMON','/assets/items/satchel-headset-liam.webp');
INSERT INTO spunk.items VALUES ('satchel-hungry-zac','hungry zac','UNCOMMON','/assets/items/satchel-hungry-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-illuminati-ash','illuminati ash','MYTHIC','/assets/items/satchel-illuminati-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-jared','jared','COMMON','/assets/items/satchel-jared.webp');
INSERT INTO spunk.items VALUES ('satchel-liam-p','liam P','COMMON','/assets/items/satchel-liam-p.webp');
INSERT INTO spunk.items VALUES ('satchel-lolipop-ash','lolipop ash','COMMON','/assets/items/satchel-lolipop-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-long-neck-ash','long neck ash','UNCOMMON','/assets/items/satchel-long-neck-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-nipslip-haz','nipslip haz','COMMON','/assets/items/satchel-nipslip-haz.webp');
INSERT INTO spunk.items VALUES ('satchel-no-body-cam-since-belmont-road','no body cam since belmont road','COMMON','/assets/items/satchel-no-body-cam-since-belmont-road.webp');
INSERT INTO spunk.items VALUES ('satchel-paintjob-haz','paintjob haz','RARE','/assets/items/satchel-paintjob-haz.webp');
INSERT INTO spunk.items VALUES ('satchel-pdf-ash','pdf ash','COMMON','/assets/items/satchel-pdf-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-pepperoni-haz','pepperoni haz','COMMON','/assets/items/satchel-pepperoni-haz.webp');
INSERT INTO spunk.items VALUES ('satchel-prom-fellas','prom fellas','RARE','/assets/items/satchel-prom-fellas.webp');
INSERT INTO spunk.items VALUES ('satchel-shocked-zac','shocked zac','UNCOMMON','/assets/items/satchel-shocked-zac.webp');
INSERT INTO spunk.items VALUES ('satchel-skinfade-ash','skinfade ash','COMMON','/assets/items/satchel-skinfade-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-slender-haz','slender haz','COMMON','/assets/items/satchel-slender-haz.webp');
INSERT INTO spunk.items VALUES ('satchel-snoty-dave','snoty dave','COMMON','/assets/items/satchel-snoty-dave.webp');
INSERT INTO spunk.items VALUES ('satchel-special-train-ride','special train ride','EPIC','/assets/items/satchel-special-train-ride.webp');
INSERT INTO spunk.items VALUES ('satchel-stupid-wall-photo','stupid wall photo','COMMON','/assets/items/satchel-stupid-wall-photo.webp');
INSERT INTO spunk.items VALUES ('satchel-suited-up-ash','suited up ash','UNCOMMON','/assets/items/satchel-suited-up-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-thinker-ash','thinker ash','RARE','/assets/items/satchel-thinker-ash.webp');
INSERT INTO spunk.items VALUES ('satchel-what-went-wrong','what went wrong','UNCOMMON','/assets/items/satchel-what-went-wrong.webp');
INSERT INTO spunk.cases VALUES ('basic','SPUNK CASE - BASIC',20,true);
INSERT INTO spunk.case_items VALUES ('basic','angry-ash',1.1250000000000002);
INSERT INTO spunk.case_items VALUES ('basic','drag-ttg',0.625);
INSERT INTO spunk.case_items VALUES ('basic','mike-andy-and-shuan',1.25);
INSERT INTO spunk.case_items VALUES ('basic','mini-men',0.8695652173913043);
INSERT INTO spunk.case_items VALUES ('basic','ttg-nip-slip',0.13043478260869565);
INSERT INTO spunk.case_items VALUES ('basic','chicken-troopers',1.0769230769230769);
INSERT INTO spunk.case_items VALUES ('basic','jamie-g',1.3461538461538463);
INSERT INTO spunk.case_items VALUES ('basic','johnpork',1.3461538461538463);
INSERT INTO spunk.case_items VALUES ('basic','wonkey-ash',3.230769230769231);
INSERT INTO spunk.case_items VALUES ('basic','leonardo',3.087719298245614);
INSERT INTO spunk.case_items VALUES ('basic','mike',3.6491228070175437);
INSERT INTO spunk.case_items VALUES ('basic','pencil-arms-ash',2.526315789473684);
INSERT INTO spunk.case_items VALUES ('basic','surfing-haz',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('basic','ttgdressup',4.0701754385964914);
INSERT INTO spunk.case_items VALUES ('basic','chud-zac',6.953020134228188);
INSERT INTO spunk.case_items VALUES ('basic','dodgyhaz',6.389261744966443);
INSERT INTO spunk.case_items VALUES ('basic','hardhat-zac',6.201342281879195);
INSERT INTO spunk.case_items VALUES ('basic','shuan',8.456375838926174);
INSERT INTO spunk.case_items VALUES ('basic','cashire-ttg',9.473684210526315);
INSERT INTO spunk.case_items VALUES ('basic','forkbev',11.052631578947368);
INSERT INTO spunk.case_items VALUES ('basic','tony',11.25);
INSERT INTO spunk.case_items VALUES ('basic','ttg',13.223684210526315);
INSERT INTO spunk.cases VALUES ('ash','ASH CASE',100,true);
INSERT INTO spunk.case_items VALUES ('ash','ash-ash-paffet',7);
INSERT INTO spunk.case_items VALUES ('ash','ash-aura-farm-ash',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('ash','ash-bald-ash',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('ash','ash-bannana-ash',15);
INSERT INTO spunk.case_items VALUES ('ash','ash-blue-bag-ash',15);
INSERT INTO spunk.case_items VALUES ('ash','ash-caveman-ash',7);
INSERT INTO spunk.case_items VALUES ('ash','ash-cheeky-ash',7);
INSERT INTO spunk.case_items VALUES ('ash','ash-chocolate-milk-ash',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('ash','ash-clipper-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-egg-ash',0.6);
INSERT INTO spunk.case_items VALUES ('ash','ash-football-ash',0.6);
INSERT INTO spunk.case_items VALUES ('ash','ash-frustrated-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-gate-ash',15);
INSERT INTO spunk.case_items VALUES ('ash','ash-goalkeeper-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-horny-ash',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('ash','ash-hotdog-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-mars-bar-ash',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('ash','ash-obese-ash',0.6);
INSERT INTO spunk.case_items VALUES ('ash','ash-posture-ash',0.6);
INSERT INTO spunk.case_items VALUES ('ash','ash-rude-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-sleepy-ash',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('ash','ash-seductive-ash',7);
INSERT INTO spunk.case_items VALUES ('ash','ash-supercool-young-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-taking-it-ash',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('ash','ash-the-gang-ash',0.6);
INSERT INTO spunk.case_items VALUES ('ash','ash-thumbs-up-ash',1);
INSERT INTO spunk.case_items VALUES ('ash','ash-ttt-ash',2.6666666666666665);
INSERT INTO spunk.case_items VALUES ('ash','ash-workout-ash',2.6666666666666665);
INSERT INTO spunk.cases VALUES ('satchel','SEMEN SATCHEL',150,true);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-a-h',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-ash-kyle-show',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-bathtub-boys',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-bev-and-the-bean-stalk',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-biker-bev',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-boys-4-life',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-bright-future',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-dodgy-elevator-ride',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-erm-idk',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-game-time',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-happy-zac',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-ima-celeb-ttg',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-mafia',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-nerf-gun-ttg',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-packet-man',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-postman-jay',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-shocked-ttg',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-ttg-funeral',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-ttg-files',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-ttg-s-football-club',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-thumbs-up-ash',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-tiktok-live-ttg',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-w-rizz',0.5);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-wise-ttg-words',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-alien-abduction-zac',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-bird-zac',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-cheeky-ash',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-chicken-bomber',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-corona-ash',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-dodgy-zac',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-dont-get-cuaght',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-double-thumbs-up-ash',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-drunk-haz',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-dumptruck-zac',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-fat-slob',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-harry-myatt',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-headset-liam',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-hungry-zac',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-illuminati-ash',0.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-jared',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-liam-p',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-lolipop-ash',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-long-neck-ash',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-nipslip-haz',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-no-body-cam-since-belmont-road',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-paintjob-haz',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-pdf-ash',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-pepperoni-haz',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-prom-fellas',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-shocked-zac',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-skinfade-ash',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-slender-haz',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-snoty-dave',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-special-train-ride',0.875);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-stupid-wall-photo',2.6470588235294117);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-suited-up-ash',2.3333333333333335);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-thinker-ash',1.3333333333333333);
INSERT INTO spunk.case_items VALUES ('satchel','satchel-what-went-wrong',2.3333333333333335);
INSERT INTO spunk.lines VALUES ('ttg','TTG LINE',750000);
INSERT INTO spunk.line_items VALUES ('ttg','ttg');
INSERT INTO spunk.line_items VALUES ('ttg','cashire-ttg');
INSERT INTO spunk.line_items VALUES ('ttg','drag-ttg');
INSERT INTO spunk.line_items VALUES ('ttg','ttgdressup');
INSERT INTO spunk.line_items VALUES ('ttg','ttg-nip-slip');
INSERT INTO spunk.lines VALUES ('ash','ASH LINE',150000);
INSERT INTO spunk.line_items VALUES ('ash','angry-ash');
INSERT INTO spunk.line_items VALUES ('ash','pencil-arms-ash');
INSERT INTO spunk.line_items VALUES ('ash','wonkey-ash');
INSERT INTO spunk.lines VALUES ('shuan','SHUAN LINE',150000);
INSERT INTO spunk.line_items VALUES ('shuan','shuan');
INSERT INTO spunk.line_items VALUES ('shuan','mike-andy-and-shuan');
INSERT INTO spunk.lines VALUES ('zac','ZAC LINE',25000);
INSERT INTO spunk.line_items VALUES ('zac','chud-zac');
INSERT INTO spunk.line_items VALUES ('zac','hardhat-zac');
INSERT INTO spunk.lines VALUES ('haz','HAZ LINE',50000);
INSERT INTO spunk.line_items VALUES ('haz','dodgyhaz');
INSERT INTO spunk.line_items VALUES ('haz','surfing-haz');
INSERT INTO spunk.lines VALUES ('mike','MIKE LINE',150000);
INSERT INTO spunk.line_items VALUES ('mike','mike');
INSERT INTO spunk.line_items VALUES ('mike','mike-andy-and-shuan');
INSERT INTO spunk.settings(id,value) VALUES(1,'{"startingBalance":2000,"dailyReward":500,"firstCaseReward":250,"caseReward":50,"duplicateReward":100,"freeReward":500,"rarityRewards":{"COMMON":5000,"UNCOMMON":10000,"RARE":20000,"EPIC":40000,"LEGENDARY":100000,"MYTHIC":500000},"upgradeChances":{"2":50,"5":10,"10":5,"20":2.5,"1.5":65}}'::jsonb);
END $seed$;
