-- Initial seed only. Safe to rerun: never resets player progress or edited settings.
DO $seed$ BEGIN
IF EXISTS (SELECT 1 FROM spunk.settings WHERE id=1) THEN RETURN; END IF;
INSERT INTO spunk.items VALUES ('angry-ash','Angry Ash','LEGENDARY','/assets/items/Angry%20Ash.png');
INSERT INTO spunk.items VALUES ('drag-ttg','Drag TTG','LEGENDARY','/assets/items/Drag%20TTG.png');
INSERT INTO spunk.items VALUES ('mike-andy-and-shuan','mike andy and shuan','LEGENDARY','/assets/items/mike%20andy%20and%20shuan.png');
INSERT INTO spunk.items VALUES ('mini-men','mini men','MYTHIC','/assets/items/mini%20men.png');
INSERT INTO spunk.items VALUES ('ttg-nip-slip','TTG NIP SLIP','MYTHIC','/assets/items/TTG%20NIP%20SLIP.jpg');
INSERT INTO spunk.items VALUES ('chicken-troopers','chicken troopers','EPIC','/assets/items/chicken%20troopers.png');
INSERT INTO spunk.items VALUES ('jamie-g','Jamie G','EPIC','/assets/items/Jamie%20G.png');
INSERT INTO spunk.items VALUES ('johnpork','johnpork','EPIC','/assets/items/johnpork.png');
INSERT INTO spunk.items VALUES ('wonkey-ash','wonkey ash','EPIC','/assets/items/wonkey%20ash.jpg');
INSERT INTO spunk.items VALUES ('leonardo','leonardo','RARE','/assets/items/leonardo.png');
INSERT INTO spunk.items VALUES ('mike','mike','RARE','/assets/items/mike.jpg');
INSERT INTO spunk.items VALUES ('pencil-arms-ash','pencil arms ash','RARE','/assets/items/pencil%20arms%20ash.png');
INSERT INTO spunk.items VALUES ('surfing-haz','surfing haz','RARE','/assets/items/surfing%20haz.png');
INSERT INTO spunk.items VALUES ('ttgdressup','TTGDRESSup','RARE','/assets/items/TTGDRESSup.png');
INSERT INTO spunk.items VALUES ('chud-zac','Chud Zac','UNCOMMON','/assets/items/Chud%20Zac.jpg');
INSERT INTO spunk.items VALUES ('dodgyhaz','dodgyHaz','UNCOMMON','/assets/items/dodgyHaz.png');
INSERT INTO spunk.items VALUES ('hardhat-zac','HardHat Zac','UNCOMMON','/assets/items/HardHat%20Zac.png');
INSERT INTO spunk.items VALUES ('shuan','Shuan','UNCOMMON','/assets/items/Shuan.png');
INSERT INTO spunk.items VALUES ('cashire-ttg','Cashire TTG','COMMON','/assets/items/Cashire%20TTG.png');
INSERT INTO spunk.items VALUES ('forkbev','ForkBev','COMMON','/assets/items/ForkBev.png');
INSERT INTO spunk.items VALUES ('tony','Tony','COMMON','/assets/items/Tony.png');
INSERT INTO spunk.items VALUES ('ttg','TTG','COMMON','/assets/items/TTG.png');
INSERT INTO spunk.cases VALUES ('basic','SPUNK CASE - BASIC',500,true);
INSERT INTO spunk.case_items VALUES ('basic','angry-ash',0.65625);
INSERT INTO spunk.case_items VALUES ('basic','drag-ttg',0.36458333333333337);
INSERT INTO spunk.case_items VALUES ('basic','mike-andy-and-shuan',0.7291666666666667);
INSERT INTO spunk.case_items VALUES ('basic','mini-men',0.21739130434782608);
INSERT INTO spunk.case_items VALUES ('basic','ttg-nip-slip',0.03260869565217391);
INSERT INTO spunk.case_items VALUES ('basic','chicken-troopers',0.9230769230769231);
INSERT INTO spunk.case_items VALUES ('basic','jamie-g',1.1538461538461537);
INSERT INTO spunk.case_items VALUES ('basic','johnpork',1.1538461538461537);
INSERT INTO spunk.case_items VALUES ('basic','wonkey-ash',2.769230769230769);
INSERT INTO spunk.case_items VALUES ('basic','leonardo',2.508771929824561);
INSERT INTO spunk.case_items VALUES ('basic','mike',2.9649122807017543);
INSERT INTO spunk.case_items VALUES ('basic','pencil-arms-ash',2.0526315789473686);
INSERT INTO spunk.case_items VALUES ('basic','surfing-haz',2.1666666666666665);
INSERT INTO spunk.case_items VALUES ('basic','ttgdressup',3.307017543859649);
INSERT INTO spunk.case_items VALUES ('basic','chud-zac',6.704697986577181);
INSERT INTO spunk.case_items VALUES ('basic','dodgyhaz',6.1610738255033555);
INSERT INTO spunk.case_items VALUES ('basic','hardhat-zac',5.97986577181208);
INSERT INTO spunk.case_items VALUES ('basic','shuan',8.154362416107382);
INSERT INTO spunk.case_items VALUES ('basic','cashire-ttg',10.947368421052632);
INSERT INTO spunk.case_items VALUES ('basic','forkbev',12.771929824561404);
INSERT INTO spunk.case_items VALUES ('basic','tony',13);
INSERT INTO spunk.case_items VALUES ('basic','ttg',15.280701754385966);
INSERT INTO spunk.lines VALUES ('ttg','TTG LINE',750000);
INSERT INTO spunk.line_items VALUES ('ttg','ttg');
INSERT INTO spunk.line_items VALUES ('ttg','cashire-ttg');
INSERT INTO spunk.line_items VALUES ('ttg','drag-ttg');
INSERT INTO spunk.line_items VALUES ('ttg','ttgdressup');
INSERT INTO spunk.line_items VALUES ('ttg','ttg-nip-slip');
INSERT INTO spunk.lines VALUES ('ash','ASH LINE',150000);
INSERT INTO spunk.line_items VALUES ('ash','angry-ash');
INSERT INTO spunk.line_items VALUES ('ash','pencil-arms-ash');
INSERT INTO spunk.line_items VALUES ('ash','wonkey-ash');
INSERT INTO spunk.lines VALUES ('shuan','SHUAN LINE',150000);
INSERT INTO spunk.line_items VALUES ('shuan','shuan');
INSERT INTO spunk.line_items VALUES ('shuan','mike-andy-and-shuan');
INSERT INTO spunk.lines VALUES ('zac','ZAC LINE',25000);
INSERT INTO spunk.line_items VALUES ('zac','chud-zac');
INSERT INTO spunk.line_items VALUES ('zac','hardhat-zac');
INSERT INTO spunk.lines VALUES ('haz','HAZ LINE',50000);
INSERT INTO spunk.line_items VALUES ('haz','dodgyhaz');
INSERT INTO spunk.line_items VALUES ('haz','surfing-haz');
INSERT INTO spunk.lines VALUES ('mike','MIKE LINE',150000);
INSERT INTO spunk.line_items VALUES ('mike','mike');
INSERT INTO spunk.line_items VALUES ('mike','mike-andy-and-shuan');
INSERT INTO spunk.settings(id,value) VALUES(1,'{"startingBalance":2000,"dailyReward":500,"firstCaseReward":250,"caseReward":50,"duplicateReward":100,"freeReward":500,"rarityRewards":{"COMMON":5000,"UNCOMMON":10000,"RARE":20000,"EPIC":40000,"LEGENDARY":100000,"MYTHIC":500000},"upgradeChances":{"2":50,"5":10,"10":5,"20":2.5,"1.5":65}}'::jsonb);
END $seed$;
