-- THE RETURN OF THE GOON: run this entire file in the Supabase SQL Editor.
-- Rerunnable. Adds the case and changes card values; never resets players,
-- balances, inventory, discoveries, completion rewards or saved game results.
BEGIN;
SELECT id FROM spunk.settings WHERE id=1 FOR UPDATE;
ALTER TABLE spunk.items ADD COLUMN IF NOT EXISTS value integer CHECK(value>0);
ALTER TABLE spunk.items ADD COLUMN IF NOT EXISTS mystery boolean NOT NULL DEFAULT false;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-arm-wresling','Arm Wrestling','MYTHIC','/assets/items/goon-arm-wresling.webp',120000,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-big-breast-haz','Big Breast Haz','LEGENDARY','/assets/items/goon-big-breast-haz.webp',140,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-blobfish-ash','BlobFish Ash','MYTHIC','/assets/items/goon-blobfish-ash.webp',100000,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-mystery-01','Border Patrol','MYTHIC','/assets/items/goon-mystery-01.webp',1000000,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-mystery-02','Boxing','MYTHIC','/assets/items/goon-mystery-02.webp',1000000,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-dodgy-dave','Dodgy Dave','EPIC','/assets/items/goon-dodgy-dave.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-fish-ash','Fish Ash','COMMON','/assets/items/goon-fish-ash.webp',145,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-gary-post','Gary Post','RARE','/assets/items/goon-gary-post.webp',15,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-goon-face-ash','Goon Face Ash','LEGENDARY','/assets/items/goon-goon-face-ash.webp',140,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-hard-work-zac','Hard Work Zac','EPIC','/assets/items/goon-hard-work-zac.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-island-boys','Island Boys','RARE','/assets/items/goon-island-boys.webp',15,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-kebab-delight','Kebab Delight','UNCOMMON','/assets/items/goon-kebab-delight.webp',5,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-lippy','Lippy','EPIC','/assets/items/goon-lippy.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-open-wide','Open Wide','EPIC','/assets/items/goon-open-wide.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-photogenic-ash','Photogenic Ash','COMMON','/assets/items/goon-photogenic-ash.webp',145,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-slobbery-smile','Slobbery Smile','LEGENDARY','/assets/items/goon-slobbery-smile.webp',140,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-taking-it-zac','Taking It Zac','EPIC','/assets/items/goon-taking-it-zac.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.items(id,name,rarity,image,value,mystery) VALUES('goon-tripple-chin-tart','Triple Chin Tart','EPIC','/assets/items/goon-tripple-chin-tart.webp',35,false) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,rarity=EXCLUDED.rarity,image=EXCLUDED.image,value=EXCLUDED.value,mystery=EXCLUDED.mystery;
INSERT INTO spunk.cases(id,name,price,enabled) VALUES('goon','THE RETURN OF THE GOON',500,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,enabled=EXCLUDED.enabled;
DELETE FROM spunk.case_items WHERE case_id='goon';
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-arm-wresling',0.02);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-big-breast-haz',2);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-blobfish-ash',0.08);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-mystery-01',0.004);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-mystery-02',0.004);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-dodgy-dave',5);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-fish-ash',1.946);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-gary-post',10);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-goon-face-ash',2);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-hard-work-zac',5);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-island-boys',10);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-kebab-delight',40);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-lippy',5);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-open-wide',5);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-photogenic-ash',1.946);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-slobbery-smile',2);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-taking-it-zac',5);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('goon','goon-tripple-chin-tart',5);
-- Reprice existing cards only. Existing photos, names and ownership stay intact.
UPDATE spunk.items SET value=335 WHERE id='angry-ash';
UPDATE spunk.items SET value=810 WHERE id='drag-ttg';
UPDATE spunk.items SET value=285 WHERE id='mike-andy-and-shuan';
UPDATE spunk.items SET value=495 WHERE id='mini-men';
UPDATE spunk.items SET value=8490 WHERE id='ttg-nip-slip';
UPDATE spunk.items SET value=360 WHERE id='chicken-troopers';
UPDATE spunk.items SET value=255 WHERE id='jamie-g';
UPDATE spunk.items SET value=255 WHERE id='johnpork';
UPDATE spunk.items SET value=70 WHERE id='wonkey-ash';
UPDATE spunk.items SET value=75 WHERE id='leonardo';
UPDATE spunk.items SET value=55 WHERE id='mike';
UPDATE spunk.items SET value=100 WHERE id='pencil-arms-ash';
UPDATE spunk.items SET value=90 WHERE id='surfing-haz';
UPDATE spunk.items SET value=50 WHERE id='ttgdressup';
UPDATE spunk.items SET value=20 WHERE id='chud-zac';
UPDATE spunk.items SET value=25 WHERE id='dodgyhaz';
UPDATE spunk.items SET value=25 WHERE id='hardhat-zac';
UPDATE spunk.items SET value=15 WHERE id='shuan';
UPDATE spunk.items SET value=15 WHERE id='cashire-ttg';
UPDATE spunk.items SET value=10 WHERE id='forkbev';
UPDATE spunk.items SET value=10 WHERE id='tony';
UPDATE spunk.items SET value=10 WHERE id='ttg';
UPDATE spunk.items SET value=20 WHERE id='ash-ash-paffet';
UPDATE spunk.items SET value=2080 WHERE id='ash-aura-farm-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-bald-ash';
UPDATE spunk.items SET value=5 WHERE id='ash-bannana-ash';
UPDATE spunk.items SET value=5 WHERE id='ash-blue-bag-ash';
UPDATE spunk.items SET value=20 WHERE id='ash-caveman-ash';
UPDATE spunk.items SET value=20 WHERE id='ash-cheeky-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-chocolate-milk-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-clipper-ash';
UPDATE spunk.items SET value=860 WHERE id='ash-egg-ash';
UPDATE spunk.items SET value=860 WHERE id='ash-football-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-frustrated-ash';
UPDATE spunk.items SET value=5 WHERE id='ash-gate-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-goalkeeper-ash';
UPDATE spunk.items SET value=2080 WHERE id='ash-horny-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-hotdog-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-mars-bar-ash';
UPDATE spunk.items SET value=860 WHERE id='ash-obese-ash';
UPDATE spunk.items SET value=860 WHERE id='ash-posture-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-rude-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-sleepy-ash';
UPDATE spunk.items SET value=20 WHERE id='ash-seductive-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-supercool-young-ash';
UPDATE spunk.items SET value=2080 WHERE id='ash-taking-it-ash';
UPDATE spunk.items SET value=860 WHERE id='ash-the-gang-ash';
UPDATE spunk.items SET value=400 WHERE id='ash-thumbs-up-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-ttt-ash';
UPDATE spunk.items SET value=90 WHERE id='ash-workout-ash';
UPDATE spunk.items SET value=260 WHERE id='satchel-a-h';
UPDATE spunk.items SET value=490 WHERE id='satchel-ash-kyle-show';
UPDATE spunk.items SET value=490 WHERE id='satchel-bathtub-boys';
UPDATE spunk.items SET value=1130 WHERE id='satchel-bev-and-the-bean-stalk';
UPDATE spunk.items SET value=260 WHERE id='satchel-biker-bev';
UPDATE spunk.items SET value=1130 WHERE id='satchel-boys-4-life';
UPDATE spunk.items SET value=490 WHERE id='satchel-bright-future';
UPDATE spunk.items SET value=260 WHERE id='satchel-dodgy-elevator-ride';
UPDATE spunk.items SET value=260 WHERE id='satchel-erm-idk';
UPDATE spunk.items SET value=490 WHERE id='satchel-game-time';
UPDATE spunk.items SET value=260 WHERE id='satchel-happy-zac';
UPDATE spunk.items SET value=490 WHERE id='satchel-ima-celeb-ttg';
UPDATE spunk.items SET value=1130 WHERE id='satchel-mafia';
UPDATE spunk.items SET value=260 WHERE id='satchel-nerf-gun-ttg';
UPDATE spunk.items SET value=110 WHERE id='satchel-packet-man';
UPDATE spunk.items SET value=110 WHERE id='satchel-postman-jay';
UPDATE spunk.items SET value=95 WHERE id='satchel-shocked-ttg';
UPDATE spunk.items SET value=1130 WHERE id='satchel-ttg-funeral';
UPDATE spunk.items SET value=2080 WHERE id='satchel-ttg-files';
UPDATE spunk.items SET value=1130 WHERE id='satchel-ttg-s-football-club';
UPDATE spunk.items SET value=95 WHERE id='satchel-thumbs-up-ash';
UPDATE spunk.items SET value=490 WHERE id='satchel-tiktok-live-ttg';
UPDATE spunk.items SET value=1130 WHERE id='satchel-w-rizz';
UPDATE spunk.items SET value=260 WHERE id='satchel-wise-ttg-words';
UPDATE spunk.items SET value=2080 WHERE id='satchel-alien-abduction-zac';
UPDATE spunk.items SET value=260 WHERE id='satchel-bird-zac';
UPDATE spunk.items SET value=110 WHERE id='satchel-cheeky-ash';
UPDATE spunk.items SET value=490 WHERE id='satchel-chicken-bomber';
UPDATE spunk.items SET value=110 WHERE id='satchel-corona-ash';
UPDATE spunk.items SET value=95 WHERE id='satchel-dodgy-zac';
UPDATE spunk.items SET value=95 WHERE id='satchel-dont-get-cuaght';
UPDATE spunk.items SET value=110 WHERE id='satchel-double-thumbs-up-ash';
UPDATE spunk.items SET value=110 WHERE id='satchel-drunk-haz';
UPDATE spunk.items SET value=260 WHERE id='satchel-dumptruck-zac';
UPDATE spunk.items SET value=95 WHERE id='satchel-fat-slob';
UPDATE spunk.items SET value=110 WHERE id='satchel-harry-myatt';
UPDATE spunk.items SET value=95 WHERE id='satchel-headset-liam';
UPDATE spunk.items SET value=110 WHERE id='satchel-hungry-zac';
UPDATE spunk.items SET value=2080 WHERE id='satchel-illuminati-ash';
UPDATE spunk.items SET value=95 WHERE id='satchel-jared';
UPDATE spunk.items SET value=95 WHERE id='satchel-liam-p';
UPDATE spunk.items SET value=95 WHERE id='satchel-lolipop-ash';
UPDATE spunk.items SET value=110 WHERE id='satchel-long-neck-ash';
UPDATE spunk.items SET value=95 WHERE id='satchel-nipslip-haz';
UPDATE spunk.items SET value=95 WHERE id='satchel-no-body-cam-since-belmont-road';
UPDATE spunk.items SET value=260 WHERE id='satchel-paintjob-haz';
UPDATE spunk.items SET value=95 WHERE id='satchel-pdf-ash';
UPDATE spunk.items SET value=95 WHERE id='satchel-pepperoni-haz';
UPDATE spunk.items SET value=260 WHERE id='satchel-prom-fellas';
UPDATE spunk.items SET value=110 WHERE id='satchel-shocked-zac';
UPDATE spunk.items SET value=95 WHERE id='satchel-skinfade-ash';
UPDATE spunk.items SET value=95 WHERE id='satchel-slender-haz';
UPDATE spunk.items SET value=95 WHERE id='satchel-snoty-dave';
UPDATE spunk.items SET value=490 WHERE id='satchel-special-train-ride';
UPDATE spunk.items SET value=95 WHERE id='satchel-stupid-wall-photo';
UPDATE spunk.items SET value=110 WHERE id='satchel-suited-up-ash';
UPDATE spunk.items SET value=260 WHERE id='satchel-thinker-ash';
UPDATE spunk.items SET value=110 WHERE id='satchel-what-went-wrong';
-- Repair JSON written by older builds through the production driver.
UPDATE spunk.history SET detail=(detail#>>'{}')::jsonb WHERE jsonb_typeof(detail)='string';
UPDATE spunk.requests SET response=(response#>>'{}')::jsonb WHERE jsonb_typeof(response)='string';
UPDATE spunk.admin_audit SET detail=(detail#>>'{}')::jsonb WHERE jsonb_typeof(detail)='string';
UPDATE spunk.admin_requests SET response=(response#>>'{}')::jsonb WHERE jsonb_typeof(response)='string';
UPDATE spunk.settings SET value=(value#>>'{}')::jsonb WHERE jsonb_typeof(value)='string';
CREATE INDEX IF NOT EXISTS ledger_coin_results ON spunk.ledger(reference_id,player_id,created_at DESC) WHERE type IN ('COIN_FLIP_WAGER','COIN_FLIP_WIN','COIN_FLIP_LOSS');
UPDATE spunk.settings SET version=version+1 WHERE id=1;
COMMIT;
-- Verification: 18 cards, 100 total weight, 0.008% combined mystery odds.
SELECT count(*) AS goon_cards,sum(weight) AS total_weight,
 round((100*sum(weight) FILTER(WHERE i.mystery)/sum(weight))::numeric,3) AS mystery_percent
 FROM spunk.case_items c JOIN spunk.items i ON i.id=c.item_id WHERE case_id='goon';
