-- Run the complete contents once in Supabase SQL Editor BEFORE deploying v2.
-- Existing players, balances, passcodes, sessions, card counts and awards are preserved.
BEGIN;
CREATE TABLE IF NOT EXISTS spunk.migrations (id text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE spunk.migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON spunk.migrations FROM PUBLIC;
SELECT pg_advisory_xact_lock(761912);
DO $v2$ BEGIN
IF EXISTS(SELECT 1 FROM spunk.migrations WHERE id='002-ash-effects') THEN RETURN; END IF;
-- Prevent a game from observing a half-updated catalog.
PERFORM id FROM spunk.settings WHERE id=1 FOR UPDATE;
-- Additive card storage; original inventory rows stay intact.
CREATE TABLE IF NOT EXISTS spunk.discoveries (player_id text REFERENCES spunk.players(id),item_id text REFERENCES spunk.items(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(player_id,item_id));
CREATE TABLE IF NOT EXISTS spunk.card_effects (player_id text REFERENCES spunk.players(id),item_id text REFERENCES spunk.items(id),effect text NOT NULL CHECK(effect IN ('NONE','SPUNK','POO','SMEGMA')),quantity integer NOT NULL CHECK(quantity>0),PRIMARY KEY(player_id,item_id,effect));
INSERT INTO spunk.discoveries(player_id,item_id) SELECT player_id,item_id FROM spunk.player_items ON CONFLICT DO NOTHING;
INSERT INTO spunk.discoveries(player_id,item_id) SELECT player_id,item_id FROM spunk.case_openings ON CONFLICT DO NOTHING;
CREATE OR REPLACE FUNCTION spunk.remember_discovery() RETURNS trigger LANGUAGE plpgsql SET search_path=spunk,pg_temp AS $$ BEGIN
 INSERT INTO spunk.discoveries(player_id,item_id) VALUES(NEW.player_id,NEW.item_id) ON CONFLICT DO NOTHING; RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS remember_discovery ON spunk.player_items;
CREATE TRIGGER remember_discovery AFTER INSERT OR UPDATE ON spunk.player_items FOR EACH ROW EXECUTE FUNCTION spunk.remember_discovery();
ALTER TABLE spunk.discoveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE spunk.card_effects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON spunk.discoveries,spunk.card_effects FROM PUBLIC;
REVOKE ALL ON FUNCTION spunk.remember_discovery() FROM PUBLIC;

INSERT INTO spunk.items(id,name,rarity,image) VALUES('angry-ash','Angry Ash','LEGENDARY','/assets/items/angry-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('drag-ttg','Drag TTG','LEGENDARY','/assets/items/drag-ttg.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('mike-andy-and-shuan','mike andy and shuan','LEGENDARY','/assets/items/mike-andy-and-shuan.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('mini-men','mini men','MYTHIC','/assets/items/mini-men.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ttg-nip-slip','TTG NIP SLIP','MYTHIC','/assets/items/ttg-nip-slip.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('chicken-troopers','chicken troopers','EPIC','/assets/items/chicken-troopers.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('jamie-g','Jamie G','EPIC','/assets/items/jamie-g.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('johnpork','johnpork','EPIC','/assets/items/johnpork.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('wonkey-ash','wonkey ash','EPIC','/assets/items/wonkey-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('leonardo','leonardo','RARE','/assets/items/leonardo.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('mike','mike','RARE','/assets/items/mike.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('pencil-arms-ash','pencil arms ash','RARE','/assets/items/pencil-arms-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('surfing-haz','surfing haz','RARE','/assets/items/surfing-haz.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ttgdressup','TTGDRESSup','RARE','/assets/items/ttgdressup.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('chud-zac','Chud Zac','UNCOMMON','/assets/items/chud-zac.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('dodgyhaz','dodgyHaz','UNCOMMON','/assets/items/dodgyhaz.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('hardhat-zac','HardHat Zac','UNCOMMON','/assets/items/hardhat-zac.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('shuan','Shuan','UNCOMMON','/assets/items/shuan.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('cashire-ttg','Cashire TTG','COMMON','/assets/items/cashire-ttg.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('forkbev','ForkBev','COMMON','/assets/items/forkbev.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('tony','Tony','COMMON','/assets/items/tony.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ttg','TTG','COMMON','/assets/items/ttg.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-ash-paffet','ash paffet','UNCOMMON','/assets/items/ash-ash-paffet.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-aura-farm-ash','Aura Farm ash','MYTHIC','/assets/items/ash-aura-farm-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-bald-ash','Bald ash','RARE','/assets/items/ash-bald-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-bannana-ash','Bannana Ash','COMMON','/assets/items/ash-bannana-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-blue-bag-ash','blue bag ash','COMMON','/assets/items/ash-blue-bag-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-caveman-ash','caveman ash','UNCOMMON','/assets/items/ash-caveman-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-cheeky-ash','Cheeky ash','UNCOMMON','/assets/items/ash-cheeky-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-chocolate-milk-ash','Chocolate milk ash','RARE','/assets/items/ash-chocolate-milk-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-clipper-ash','Clipper Ash','EPIC','/assets/items/ash-clipper-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-egg-ash','Egg Ash','LEGENDARY','/assets/items/ash-egg-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-football-ash','Football ash','LEGENDARY','/assets/items/ash-football-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-frustrated-ash','Frustrated Ash','EPIC','/assets/items/ash-frustrated-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-gate-ash','Gate Ash','COMMON','/assets/items/ash-gate-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-goalkeeper-ash','Goalkeeper ash','EPIC','/assets/items/ash-goalkeeper-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-horny-ash','Horny ash','MYTHIC','/assets/items/ash-horny-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-hotdog-ash','Hotdog ash','EPIC','/assets/items/ash-hotdog-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-mars-bar-ash','Mars Bar Ash','RARE','/assets/items/ash-mars-bar-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-obese-ash','obese ash','LEGENDARY','/assets/items/ash-obese-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-posture-ash','posture ash','LEGENDARY','/assets/items/ash-posture-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-rude-ash','Rude Ash','EPIC','/assets/items/ash-rude-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-sleepy-ash','Sleepy Ash','RARE','/assets/items/ash-sleepy-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-seductive-ash','Seductive Ash','UNCOMMON','/assets/items/ash-seductive-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-supercool-young-ash','Supercool Young Ash','EPIC','/assets/items/ash-supercool-young-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-taking-it-ash','Taking it ash','MYTHIC','/assets/items/ash-taking-it-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-the-gang-ash','The Gang ash','LEGENDARY','/assets/items/ash-the-gang-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-thumbs-up-ash','Thumbs up ash','EPIC','/assets/items/ash-thumbs-up-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-ttt-ash','TTT ash','RARE','/assets/items/ash-ttt-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('ash-workout-ash','Workout ash','RARE','/assets/items/ash-workout-ash.webp') ON CONFLICT(id) DO UPDATE SET image=EXCLUDED.image;
INSERT INTO spunk.cases(id,name,price,enabled) VALUES('basic','SPUNK CASE - BASIC',20,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,enabled=true;
DELETE FROM spunk.case_items WHERE case_id='basic';
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','angry-ash',1.1250000000000002);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','drag-ttg',0.625);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','mike-andy-and-shuan',1.25);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','mini-men',0.8695652173913043);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','ttg-nip-slip',0.13043478260869565);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','chicken-troopers',1.0769230769230769);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','jamie-g',1.3461538461538463);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','johnpork',1.3461538461538463);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','wonkey-ash',3.230769230769231);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','leonardo',3.087719298245614);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','mike',3.6491228070175437);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','pencil-arms-ash',2.526315789473684);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','surfing-haz',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','ttgdressup',4.0701754385964914);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','chud-zac',6.953020134228188);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','dodgyhaz',6.389261744966443);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','hardhat-zac',6.201342281879195);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','shuan',8.456375838926174);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','cashire-ttg',9.473684210526315);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','forkbev',11.052631578947368);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','tony',11.25);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('basic','ttg',13.223684210526315);
INSERT INTO spunk.cases(id,name,price,enabled) VALUES('ash','ASH CASE',100,true) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,enabled=true;
DELETE FROM spunk.case_items WHERE case_id='ash';
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-ash-paffet',7);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-aura-farm-ash',0.3333333333333333);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-bald-ash',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-bannana-ash',15);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-blue-bag-ash',15);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-caveman-ash',7);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-cheeky-ash',7);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-chocolate-milk-ash',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-clipper-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-egg-ash',0.6);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-football-ash',0.6);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-frustrated-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-gate-ash',15);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-goalkeeper-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-horny-ash',0.3333333333333333);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-hotdog-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-mars-bar-ash',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-obese-ash',0.6);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-posture-ash',0.6);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-rude-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-sleepy-ash',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-seductive-ash',7);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-supercool-young-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-taking-it-ash',0.3333333333333333);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-the-gang-ash',0.6);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-thumbs-up-ash',1);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-ttt-ash',2.6666666666666665);
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('ash','ash-workout-ash',2.6666666666666665);
UPDATE spunk.settings SET version=version+1 WHERE id=1;
INSERT INTO spunk.migrations(id) VALUES('002-ash-effects');
END $v2$;
COMMIT;
BEGIN;
SELECT pg_advisory_xact_lock(761912);
DO $satchel$ BEGIN
IF EXISTS(SELECT 1 FROM spunk.migrations WHERE id='003-satchel') THEN RETURN; END IF;
PERFORM id FROM spunk.settings WHERE id=1 FOR UPDATE;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-a-h','A&H','RARE','/assets/items/satchel-a-h.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-ash-kyle-show','Ash kyle show','EPIC','/assets/items/satchel-ash-kyle-show.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-bathtub-boys','Bathtub boys','EPIC','/assets/items/satchel-bathtub-boys.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-bev-and-the-bean-stalk','Bev and the Bean Stalk','LEGENDARY','/assets/items/satchel-bev-and-the-bean-stalk.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-biker-bev','Biker bev','RARE','/assets/items/satchel-biker-bev.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-boys-4-life','Boys 4 Life','LEGENDARY','/assets/items/satchel-boys-4-life.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-bright-future','Bright Future','EPIC','/assets/items/satchel-bright-future.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-dodgy-elevator-ride','Dodgy Elevator ride','RARE','/assets/items/satchel-dodgy-elevator-ride.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-erm-idk','Erm IDK','RARE','/assets/items/satchel-erm-idk.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-game-time','Game Time','EPIC','/assets/items/satchel-game-time.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-happy-zac','Happy Zac','RARE','/assets/items/satchel-happy-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-ima-celeb-ttg','Ima Celeb TTG','EPIC','/assets/items/satchel-ima-celeb-ttg.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-mafia','Mafia','LEGENDARY','/assets/items/satchel-mafia.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-nerf-gun-ttg','Nerf Gun TTG','RARE','/assets/items/satchel-nerf-gun-ttg.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-packet-man','Packet man','UNCOMMON','/assets/items/satchel-packet-man.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-postman-jay','Postman Jay','UNCOMMON','/assets/items/satchel-postman-jay.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-shocked-ttg','Shocked TTG','COMMON','/assets/items/satchel-shocked-ttg.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-ttg-funeral','TTG FUNERAL','LEGENDARY','/assets/items/satchel-ttg-funeral.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-ttg-files','TTG Files','MYTHIC','/assets/items/satchel-ttg-files.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-ttg-s-football-club','TTG''s Football club','LEGENDARY','/assets/items/satchel-ttg-s-football-club.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-thumbs-up-ash','Thumbs up ash','COMMON','/assets/items/satchel-thumbs-up-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-tiktok-live-ttg','TikTok Live TTG','EPIC','/assets/items/satchel-tiktok-live-ttg.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-w-rizz','W RIZZ','LEGENDARY','/assets/items/satchel-w-rizz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-wise-ttg-words','Wise TTg words','RARE','/assets/items/satchel-wise-ttg-words.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-alien-abduction-zac','alien abduction zac','MYTHIC','/assets/items/satchel-alien-abduction-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-bird-zac','bird zac','RARE','/assets/items/satchel-bird-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-cheeky-ash','cheeky ash','UNCOMMON','/assets/items/satchel-cheeky-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-chicken-bomber','chicken Bomber','EPIC','/assets/items/satchel-chicken-bomber.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-corona-ash','corona ash','UNCOMMON','/assets/items/satchel-corona-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-dodgy-zac','dodgy zac','COMMON','/assets/items/satchel-dodgy-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-dont-get-cuaght','dont get cuaght','COMMON','/assets/items/satchel-dont-get-cuaght.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-double-thumbs-up-ash','double thumbs up ash','UNCOMMON','/assets/items/satchel-double-thumbs-up-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-drunk-haz','drunk haz','UNCOMMON','/assets/items/satchel-drunk-haz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-dumptruck-zac','dumptruck zac','RARE','/assets/items/satchel-dumptruck-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-fat-slob','fat slob','COMMON','/assets/items/satchel-fat-slob.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-harry-myatt','harry myatt','UNCOMMON','/assets/items/satchel-harry-myatt.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-headset-liam','headset liam','COMMON','/assets/items/satchel-headset-liam.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-hungry-zac','hungry zac','UNCOMMON','/assets/items/satchel-hungry-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-illuminati-ash','illuminati ash','MYTHIC','/assets/items/satchel-illuminati-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-jared','jared','COMMON','/assets/items/satchel-jared.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-liam-p','liam P','COMMON','/assets/items/satchel-liam-p.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-lolipop-ash','lolipop ash','COMMON','/assets/items/satchel-lolipop-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-long-neck-ash','long neck ash','UNCOMMON','/assets/items/satchel-long-neck-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-nipslip-haz','nipslip haz','COMMON','/assets/items/satchel-nipslip-haz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-no-body-cam-since-belmont-road','no body cam since belmont road','COMMON','/assets/items/satchel-no-body-cam-since-belmont-road.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-paintjob-haz','paintjob haz','RARE','/assets/items/satchel-paintjob-haz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-pdf-ash','pdf ash','COMMON','/assets/items/satchel-pdf-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-pepperoni-haz','pepperoni haz','COMMON','/assets/items/satchel-pepperoni-haz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-prom-fellas','prom fellas','RARE','/assets/items/satchel-prom-fellas.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-shocked-zac','shocked zac','UNCOMMON','/assets/items/satchel-shocked-zac.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-skinfade-ash','skinfade ash','COMMON','/assets/items/satchel-skinfade-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-slender-haz','slender haz','COMMON','/assets/items/satchel-slender-haz.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-snoty-dave','snoty dave','COMMON','/assets/items/satchel-snoty-dave.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-special-train-ride','special train ride','EPIC','/assets/items/satchel-special-train-ride.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-stupid-wall-photo','stupid wall photo','COMMON','/assets/items/satchel-stupid-wall-photo.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-suited-up-ash','suited up ash','UNCOMMON','/assets/items/satchel-suited-up-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-thinker-ash','thinker ash','RARE','/assets/items/satchel-thinker-ash.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.items(id,name,rarity,image) VALUES('satchel-what-went-wrong','what went wrong','UNCOMMON','/assets/items/satchel-what-went-wrong.webp') ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.cases(id,name,price,enabled) VALUES('satchel','SEMEN SATCHEL',150,true) ON CONFLICT(id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-a-h',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-ash-kyle-show',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-bathtub-boys',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-bev-and-the-bean-stalk',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-biker-bev',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-boys-4-life',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-bright-future',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-dodgy-elevator-ride',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-erm-idk',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-game-time',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-happy-zac',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-ima-celeb-ttg',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-mafia',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-nerf-gun-ttg',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-packet-man',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-postman-jay',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-shocked-ttg',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-ttg-funeral',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-ttg-files',0.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-ttg-s-football-club',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-thumbs-up-ash',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-tiktok-live-ttg',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-w-rizz',0.5) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-wise-ttg-words',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-alien-abduction-zac',0.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-bird-zac',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-cheeky-ash',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-chicken-bomber',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-corona-ash',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-dodgy-zac',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-dont-get-cuaght',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-double-thumbs-up-ash',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-drunk-haz',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-dumptruck-zac',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-fat-slob',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-harry-myatt',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-headset-liam',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-hungry-zac',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-illuminati-ash',0.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-jared',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-liam-p',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-lolipop-ash',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-long-neck-ash',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-nipslip-haz',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-no-body-cam-since-belmont-road',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-paintjob-haz',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-pdf-ash',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-pepperoni-haz',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-prom-fellas',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-shocked-zac',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-skinfade-ash',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-slender-haz',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-snoty-dave',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-special-train-ride',0.875) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-stupid-wall-photo',2.6470588235294117) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-suited-up-ash',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-thinker-ash',1.3333333333333333) ON CONFLICT(case_id,item_id) DO NOTHING;
INSERT INTO spunk.case_items(case_id,item_id,weight) VALUES('satchel','satchel-what-went-wrong',2.3333333333333335) ON CONFLICT(case_id,item_id) DO NOTHING;
UPDATE spunk.settings SET version=version+1 WHERE id=1;
INSERT INTO spunk.migrations(id) VALUES('003-satchel');
END $satchel$;
COMMIT;
